apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: boards
spec:
  hosts:
  - boards
  http:
  - fault:
      delay:
        fixedDelay: 5s
        percentage:
          value: 100
      abort:
        httpStatus: 503
        percent: 0
    route:
    - destination:
        host: boards