apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: app-ui
spec:
  host: app-ui
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: boards
spec:
  host: boards
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: context-scraper
spec:
  host: context-scraper