apiVersion: istio.openshift.com/v1alpha3
kind: ControlPlane
metadata:
  name: istio-demo
spec:
  launcher:
    enabled: false
    # specify the url to master, e.g. https://master.some.domain.com:443
    LAUNCHER_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL: https://xxx.xxx.com
    # Your GitHub username
    LAUNCHER_MISSIONCONTROL_GITHUB_USERNAME: x
    # Your GitHub Mission Control access token
    LAUNCHER_MISSIONCONTROL_GITHUB_TOKEN: x

  threeScale:
    enabled: false
    PARAM_THREESCALE_LISTEN_ADDR: 3333
    PARAM_THREESCALE_LOG_LEVEL: info
    PARAM_THREESCALE_LOG_JSON: true
    PARAM_THREESCALE_REPORT_METRICS: true
    PARAM_THREESCALE_METRICS_PORT: 8080
    PARAM_THREESCALE_CACHE_TTL_SECONDS: 300
    PARAM_THREESCALE_CACHE_REFRESH_SECONDS: 180
    PARAM_THREESCALE_CACHE_ENTRIES_MAX: 1000
    PARAM_THREESCALE_CACHE_REFRESH_RETRIES: 1
    PARAM_THREESCALE_ALLOW_INSECURE_CONN: false
    PARAM_THREESCALE_CLIENT_TIMEOUT_SECONDS: 10

  istio:
    global:
      hub: openshift-istio-tech-preview
      tag: 0.10.0
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi
      mtls: true
      disablePolicyChecks: true
      policyCheckFailOpen: false
      # imagePullSecrets:
      #   - MyPullSecret

    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
        autoscaleMin: 1
        autoscaleMax: 5
      istio-ingressgateway:
        autoscaleEnabled: false
        autoscaleMin: 1
        autoscaleMax: 5
        ior_enabled: false

    mixer:
      policy:
        autoscaleEnabled: false

      telemetry:
        autoscaleEnabled: false
        resources:
          requests:
            cpu: 100m
            memory: 1G
          limits:
            cpu: 500m
            memory: 4G

    pilot:
      autoscaleEnabled: false
      traceSampling: 100.0

    kiali:
      enabled: true
      hub: kiali
      tag: v0.16.2
      dashboard:
        user: admin
        passphrase: admin

    tracing:
      enabled: true